(function(){'use strict';
const API=(window.SAKAN_API_BASE||localStorage.getItem('sakanApiBase')||'/api').replace(/\/$/,'');
const token=()=>localStorage.getItem('sakanAuthToken')||'';
function render(ad){const box=document.getElementById('featuredAdLive');if(!box)return;if(!ad){box.classList.add('hidden');return}box.classList.remove('hidden');box.innerHTML='<button type="button" class="featured-live-card" aria-label="فتح ملف العضو"><img src="'+ad.imageUrl+'" alt="صورة عضو معلن"><span>'+String(ad.displayName||'عضو سكن').replace(/[<>]/g,'')+'</span></button><small>الإعلان المميز · '+Math.max(0,Number(ad.remainingSeconds||0))+' ثانية</small>';box.querySelector('button').onclick=function(){location.href='member-profile.html?memberId='+encodeURIComponent(ad.memberId||'')};}
async function active(){try{const r=await fetch(API+'/featured-ads/active');const d=await r.json();render(d.active)}catch(e){}}
async function verifyPayment(){const p=new URLSearchParams(location.search);if(p.get('featured_payment')!=='success'||!p.get('session_id'))return;try{const r=await fetch(API+'/featured-ads/verify?session_id='+encodeURIComponent(p.get('session_id')),{headers:{Authorization:'Bearer '+token()}});const d=await r.json();history.replaceState({},document.title,location.pathname);alert(d.paid?'تم تأكيد الدفع. تم إدخال الصورة في طابور الإعلان.':'لم يتم تأكيد الدفع بعد.');}catch(e){alert('تعذر تأكيد الدفع.')} }
async function chooseAndPay(){if(!token()){alert('يرجى تسجيل الدخول أولًا.');return}const useProfile=confirm('اضغط موافق لاستخدام صورتك الحالية في الملف الشخصي. اضغط إلغاء لاختيار صورة أخرى من الكمبيوتر.');let body={source:'profile',imageUrl:''};if(!useProfile){const input=document.createElement('input');input.type='file';input.accept='image/*';input.click();const file=await new Promise(resolve=>{input.onchange=()=>resolve(input.files&&input.files[0]||null)});if(!file)return;if(file.size>850000){alert('اختر صورة أصغر من 850KB.');return}body.source='upload';body.imageUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});}const r=await fetch(API+'/featured-ads/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token()},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){alert(d.error||'تعذر بدء الدفع.');return}location.href=d.url}
function start(){const b=document.getElementById('featuredAdBtn');if(b)b.addEventListener('click',chooseAndPay);verifyPayment();active();setInterval(active,10000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
