(function(){'use strict';
const translations={
 ar:{'سكن':'سكن','منصة التعارف والزواج':'منصة التعارف والزواج','الرئيسية':'الرئيسية','الرسائل':'الرسائل','من زار صفحتي':'من زار صفحتي','المفضلون':'المفضلون','أحدث الأعضاء':'أحدث الأعضاء','أعضاء أونلاين':'أعضاء أونلاين','إعلانات تجارية':'إعلانات تجارية','أعلن معنا':'أعلن معنا','أعضاء جدد على سكن':'أعضاء جدد على سكن','أعضاء مقترحون':'أعضاء مقترحون','أشخاص قد يناسبونك':'أشخاص قد يناسبونك','تحديث':'تحديث','البحث عن عضو':'البحث عن عضو','تعديل بياناتي':'تعديل بياناتي','صوري':'صوري','الإعدادات':'الإعدادات','خروج':'خروج','إعلان مميز':'إعلان مميز','إعلان مميز — €0.99':'إعلان مميز — €0.99','الخصوصية':'الخصوصية','الشروط':'الشروط','بيانات المنصة':'بيانات المنصة'},
 de:{'سكن':'Sakan','منصة التعارف والزواج':'Kontakt- und Heiratsplattform','الرئيسية':'Startseite','الرسائل':'Nachrichten','من زار صفحتي':'Wer hat mein Profil besucht','المفضلون':'Favoriten','أحدث الأعضاء':'Neue Mitglieder','أعضاء أونلاين':'Online-Mitglieder','إعلانات تجارية':'Werbung','أعلن معنا':'Mit uns werben','أعضاء جدد على سكن':'Neue Mitglieder auf Sakan','أعضاء مقترحون':'Vorgeschlagene Mitglieder','أشخاص قد يناسبونك':'Personen, die zu dir passen','تحديث':'Aktualisieren','البحث عن عضو':'Mitglieder suchen','تعديل بياناتي':'Meine Daten bearbeiten','صوري':'Meine Fotos','الإعدادات':'Einstellungen','خروج':'Abmelden','إعلان مميز':'Premium-Anzeige','إعلان مميز — €0.99':'Premium-Anzeige — €0,99','الخصوصية':'Datenschutz','الشروط':'Bedingungen','بيانات المنصة':'Impressum'},
 en:{'سكن':'Sakan','منصة التعارف والزواج':'Dating & Marriage Platform','الرئيسية':'Home','الرسائل':'Messages','من زار صفحتي':'Profile Visitors','المفضلون':'Favorites','أحدث الأعضاء':'Latest Members','أعضاء أونلاين':'Online Members','إعلانات تجارية':'Commercial Ads','أعلن معنا':'Advertise With Us','أعضاء جدد على سكن':'New Sakan Members','أعضاء مقترحون':'Suggested Members','أشخاص قد يناسبونك':'People Who May Match You','تحديث':'Refresh','البحث عن عضو':'Find a Member','تعديل بياناتي':'Edit My Data','صوري':'My Photos','الإعدادات':'Settings','خروج':'Log out','إعلان مميز':'Featured Ad','إعلان مميز — €0.99':'Featured Ad — €0.99','الخصوصية':'Privacy','الشروط':'Terms','بيانات المنصة':'Platform Information'},
 fr:{'الرئيسية':'Accueil','الرسائل':'Messages','من زار صفحتي':'Visiteurs du profil','المفضلون':'Favoris','أحدث الأعضاء':'Nouveaux membres','أعضاء أونلاين':'Membres en ligne','إعلانات تجارية':'Publicité','أعلن معنا':'Annoncez avec nous','تحديث':'Actualiser','البحث عن عضو':'Rechercher un membre','تعديل بياناتي':'Modifier mes données','صوري':'Mes photos','الإعدادات':'Paramètres','خروج':'Déconnexion','إعلان مميز':'Annonce premium','الخصوصية':'Confidentialité','الشروط':'Conditions'},
 es:{'الرئيسية':'Inicio','الرسائل':'Mensajes','من زار صفحتي':'Visitantes del perfil','المفضلون':'Favoritos','أحدث الأعضاء':'Nuevos miembros','أعضاء أونلاين':'Miembros en línea','إعلانات تجارية':'Publicidad','أعلن معنا':'Anúnciate','تحديث':'Actualizar','البحث عن عضو':'Buscar miembro','تعديل بياناتي':'Editar mis datos','صوري':'Mis fotos','الإعدادات':'Configuración','خروج':'Cerrar sesión','إعلان مميز':'Anuncio destacado','الخصوصية':'Privacidad','الشروط':'Términos'},
 it:{'الرئيسية':'Home','الرسائل':'Messaggi','من زار صفحتي':'Visitatori del profilo','المفضلون':'Preferiti','أحدث الأعضاء':'Nuovi membri','أعضاء أونلاين':'Membri online','إعلانات تجارية':'Pubblicità','أعلن معنا':'Pubblicizza con noi','تحديث':'Aggiorna','البحث عن عضو':'Cerca membro','تعديل بياناتي':'Modifica dati','صوري':'Le mie foto','الإعدادات':'Impostazioni','خروج':'Esci','إعلان مميز':'Annuncio in evidenza','الخصوصية':'Privacy','الشروط':'Termini'}
};
function apply(){const lang=localStorage.getItem('sakanLanguage')||'ar';const map=translations[lang]||translations.en;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const v=n.nodeValue.trim();if(v&&map[v])n.nodeValue=n.nodeValue.replace(v,map[v])});const title=document.title.trim();if(map[title])document.title=map[title];}
window.sakanSetLanguage=function(lang){localStorage.setItem('sakanLanguage',lang);apply();};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();
})();
