(function(){'use strict';
var API=(window.SAKAN_API_BASE||localStorage.getItem('sakanApiBase')||'/api').replace(/\/$/,'');
function loadFeatured(){if(!/\/home\.html$/.test(location.pathname)||document.getElementById('sakanFeaturedScript'))return;var s=document.createElement('script');s.id='sakanFeaturedScript';s.src='../js/featured-ads.js';s.defer=true;document.body.appendChild(s)}
var LANGS=[['ar','العربية'],['de','Deutsch'],['en','English'],['fr','Français'],['es','Español'],['it','Italiano'],['nl','Nederlands'],['pt','Português'],['tr','Türkçe'],['ru','Русский'],['uk','Українська'],['pl','Polski'],['sv','Svenska'],['da','Dansk'],['no','Norsk'],['fi','Suomi'],['el','Ελληνικά'],['ro','Română'],['cs','Čeština'],['hu','Magyar']];
function saveUser(u){if(!u)return;localStorage.setItem('sakanCurrentUser',JSON.stringify(u));localStorage.setItem('sakanProfileData',JSON.stringify({realName:u.realName||'',displayName:u.displayName||'',gender:u.gender||'',birthDate:u.birthDate||'',age:u.age||'',country:u.country||'',city:u.city||'',maritalStatus:u.maritalStatus||'',language:u.language||u.preferredLanguage||'ar',education:u.education||'',profession:u.profession||'',aboutMe:u.aboutMe||'',lookingFor:u.lookingFor||'',showRealName:!!u.showRealName,preferredLanguage:u.preferredLanguage||u.language||'ar'}))}
function logo(){document.querySelectorAll('img[alt*="شعار منصة سكن"],.logo-mark img,.brand-icon img,.logo-circle img').forEach(function(i){if(i.dataset.fix)return;i.dataset.fix=1;var a=['../assets/sakan-logo.png','/frontend/assets/sakan-logo.png','/assets/sakan-logo.png'];i.addEventListener('error',function(){var n=Number(i.dataset.n||0);if(n<3){i.src=a[n];i.dataset.n=n+1}});if(!i.complete||!i.naturalWidth)i.src=a[0]})}
function sync(){var t=localStorage.getItem('sakanAuthToken'),raw=localStorage.getItem('sakanCurrentUser');if(raw){try{saveUser(JSON.parse(raw))}catch(e){}}if(!t||sessionStorage.getItem('sakanSync'))return;sessionStorage.setItem('sakanSync','1');fetch(API+'/me',{headers:{Authorization:'Bearer '+t}}).then(function(r){return r.ok?r.json():null}).then(function(d){if(d&&d.user)saveUser(d.user)}).catch(function(){})}
function oauth(){document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('#googleBtn,#facebookBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();location.assign(API+'/auth/oauth/'+(b.id==='googleBtn'?'google':'facebook')+'/start')},true)}
function lang(){var old=document.getElementById('sakanLang');if(old)old.remove();var w=document.createElement('div');w.id='sakanLang';w.style='position:fixed;top:16px;right:18px;z-index:2147483647;font-family:Arial,sans-serif';var t=document.createElement('button');t.type='button';t.textContent='🌐';t.title='اختيار اللغة';t.setAttribute('aria-label','اختيار اللغة');t.style='width:46px;height:46px;border-radius:50%;border:1px solid #c9a85b;background:#071522;color:#e4c56d;font-size:22px;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.35)';var m=document.createElement('div');m.style='display:none;position:absolute;right:0;top:54px;width:210px;max-height:360px;overflow:auto;background:#0b192b;border:1px solid #a88745;border-radius:12px;padding:6px;box-shadow:0 12px 30px rgba(0,0,0,.45)';LANGS.forEach(function(x){var q=document.createElement('button');q.type='button';q.textContent=x[1];q.style='display:block;width:100%;padding:9px 10px;margin:1px 0;background:transparent;border:0;color:#fff;text-align:right;border-radius:7px;cursor:pointer';q.onmouseenter=function(){q.style.background='rgba(216,179,93,.16)'};q.onmouseleave=function(){q.style.background='transparent'};q.onclick=function(){localStorage.setItem('sakanLanguage',x[0]);document.cookie='googtrans=/ar/'+x[0]+';path=/';document.documentElement.lang=x[0];document.documentElement.dir=x[0]==='ar'?'rtl':'ltr';var s=document.querySelector('.goog-te-combo');if(s){s.value=x[0];s.dispatchEvent(new Event('change'))}else location.reload();m.style.display='none'};m.appendChild(q)});t.onclick=function(e){e.stopPropagation();m.style.display=m.style.display==='block'?'none':'block'};document.addEventListener('click',function(){m.style.display='none'});w.append(t,m);document.body.appendChild(w);var h=document.getElementById('google_translate_element');if(!h){h=document.createElement('div');h.id='google_translate_element';h.style='position:absolute;left:-99999px;top:-99999px';document.body.appendChild(h)}window.sakanTranslateInit=function(){if(window.google&&google.translate)new google.translate.TranslateElement({pageLanguage:'ar',autoDisplay:false,includedLanguages:LANGS.map(function(x){return x[0]}).join(',')},'google_translate_element')};if(!window.google){var s=document.createElement('script');s.src='https://translate.google.com/translate_a/element.js?cb=sakanTranslateInit';s.async=true;document.body.appendChild(s)}}
function settings(){document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('.tool-card[data-tool="settings"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();location.href='settings.html'},true)}
function strip(){var t=document.getElementById('stripTrack');if(!t||t.dataset.loop)return;t.dataset.loop=1;var n=Array.from(t.children);if(!n.length)return;t.innerHTML='';var a=document.createElement('div'),c=document.createElement('div');a.className=c.className='sakanLoopGroup';n.forEach(function(x){a.appendChild(x.cloneNode(true))});n.forEach(function(x){c.appendChild(x.cloneNode(true))});t.append(a,c);var s=document.createElement('style');s.textContent='.members-strip{overflow:hidden!important}.strip-track{display:flex!important;width:max-content!important;animation:sakanLoop 38s linear infinite!important}.sakanLoopGroup{display:flex!important;gap:18px;flex-shrink:0!important}.sakanLoopGroup .mini-member{flex-shrink:0!important}@keyframes sakanLoop{from{transform:translateX(0)}to{transform:translateX(-50%)}}';document.head.appendChild(s)}
function result(){var p=new URLSearchParams(location.search),t=p.get('oauth_token');if(t){localStorage.setItem('sakanAuthToken',t);localStorage.setItem('sakanLoggedIn','true');p.delete('oauth_token');history.replaceState({},document.title,location.pathname+(p.toString()?'?'+p.toString():''));location.href='/frontend/pages/home.html'}}
function start(){result();logo();sync();oauth();lang();settings();strip();loadFeatured()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();})();
