(function(){'use strict';
var API=(window.SAKAN_API_BASE||localStorage.getItem('sakanApiBase')||'/api').replace(/\/$/,'');
var LANGS=[['ar','العربية'],['de','Deutsch'],['en','English'],['fr','Français'],['es','Español'],['it','Italiano'],['nl','Nederlands'],['pt','Português'],['tr','Türkçe'],['ru','Русский'],['uk','Українська'],['pl','Polski'],['sv','Svenska'],['da','Dansk'],['no','Norsk'],['fi','Suomi'],['el','Ελληνικά'],['ro','Română'],['cs','Čeština'],['hu','Magyar']];
function loadFeatured(){if(!/\/home\.html$/.test(location.pathname)||document.getElementById('sakanFeaturedScript'))return;var s=document.createElement('script');s.id='sakanFeaturedScript';s.src='../js/featured-ads.js';s.defer=true;document.body.appendChild(s)}
function loadInternalI18n(){if(document.getElementById('sakanInternalI18n'))return;var s=document.createElement('script');s.id='sakanInternalI18n';s.src='../js/internal-i18n.js';s.defer=true;document.body.appendChild(s)}
function saveUser(u){if(!u)return;localStorage.setItem('sakanCurrentUser',JSON.stringify(u));localStorage.setItem('sakanProfileData',JSON.stringify({realName:u.realName||'',displayName:u.displayName||'',gender:u.gender||'',birthDate:u.birthDate||'',age:u.age||'',country:u.country||'',city:u.city||'',maritalStatus:u.maritalStatus||'',language:u.language||u.preferredLanguage||'ar',education:u.education||'',profession:u.profession||'',aboutMe:u.aboutMe||'',lookingFor:u.lookingFor||'',showRealName:!!u.showRealName,preferredLanguage:u.preferredLanguage||u.language||'ar'}))}
function logo(){document.querySelectorAll('img[alt*="شعار منصة سكن"],.logo-mark img,.brand-icon img,.logo-circle img').forEach(function(i){if(i.dataset.fix)return;i.dataset.fix=1;var a=['../assets/sakan-logo.png','/frontend/assets/sakan-logo.png','/assets/sakan-logo.png'];i.addEventListener('error',function(){var n=Number(i.dataset.n||0);if(n<3){i.src=a[n];i.dataset.n=n+1}});if(!i.complete||!i.naturalWidth)i.src=a[0]})}
function sync(){var t=localStorage.getItem('sakanAuthToken'),raw=localStorage.getItem('sakanCurrentUser');if(raw){try{saveUser(JSON.parse(raw))}catch(e){}}if(!t||sessionStorage.getItem('sakanSync'))return;sessionStorage.setItem('sakanSync','1');fetch(API+'/me',{headers:{Authorization:'Bearer '+t}}).then(function(r){return r.ok?r.json():null}).then(function(d){if(d&&d.user)saveUser(d.user)}).catch(function(){})}
function oauth(){document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('#googleBtn,#facebookBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();location.assign(API+'/auth/oauth/'+(b.id==='googleBtn'?'google':'facebook')+'/start')},true)}
function lang(){var old=document.getElementById('sakanLang');if(old)old.remove();var w=document.createElement('div');w.id='sakanLang';w.style='position:fixed;top:16px;right:18px;z-index:2147483647;font-family:Arial,sans-serif';var t=document.createElement('button');t.type='button';t.textContent='🌐';t.title='اختيار اللغة';t.setAttribute('aria-label','اختيار اللغة');t.style='width:46px;height:46px;border-radius:50%;border:1px solid #c9a85b;background:#071522;color:#e4c56d;font-size:22px;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.35)';var m=document.createElement('div');m.style='display:none;position:absolute;right:0;top:54px;width:210px;max-height:360px;overflow:auto;background:#0b192b;border:1px solid #a88745;border-radius:12px;padding:6px;box-shadow:0 12px 30px rgba(0,0,0,.45)';LANGS.forEach(function(x){var q=document.createElement('button');q.type='button';q.textContent=x[1];q.style='display:block;width:100%;padding:9px 10px;margin:1px 0;background:transparent;border:0;color:#fff;text-align:right;border-radius:7px;cursor:pointer';q.onclick=function(){localStorage.setItem('sakanLanguage',x[0]);document.documentElement.lang=x[0];document.documentElement.dir=x[0]==='ar'?'rtl':'ltr';if(window.sakanSetLanguage)window.sakanSetLanguage(x[0]);m.style.display='none'};m.appendChild(q)});t.onclick=function(e){e.stopPropagation();m.style.display=m.style.display==='block'?'none':'block'};document.addEventListener('click',function(){m.style.display='none'});w.append(t,m);document.body.appendChild(w)}
function settings(){document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('.tool-card[data-tool="settings"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();location.href='settings.html'},true)}
function strip(){var t=document.getElementById('stripTrack');if(!t)return;function clean(){Array.from(t.querySelectorAll('img')).forEach(function(i){var s=((i.getAttribute('src')||'')+' '+(i.getAttribute('alt')||'')).toLowerCase();if(/sakan-logo|logo|شعار|sakan.*brand|brand.*sakan/.test(s))i.closest('.mini-member')?.remove()});t.style.animationDuration='120s';t.style.animationTimingFunction='linear';t.style.animationIterationCount='infinite';t.style.animationPlayState='running'}clean();var observer=new MutationObserver(clean);observer.observe(t,{childList:true,subtree:true});var style=document.getElementById('sakanSlowStripStyle');if(!style){style=document.createElement('style');style.id='sakanSlowStripStyle';style.textContent='.members-strip{overflow:hidden!important}.strip-track{animation-duration:120s!important;animation-timing-function:linear!important;animation-iteration-count:infinite!important}.strip-track .mini-member{transition:none!important}';document.head.appendChild(style)}}
function result(){var p=new URLSearchParams(location.search),t=p.get('oauth_token');if(t){localStorage.setItem('sakanAuthToken',t);localStorage.setItem('sakanLoggedIn','true');p.delete('oauth_token');history.replaceState({},document.title,location.pathname+(p.toString()?'?'+p.toString():''));location.href='/frontend/pages/home.html'}}
function start(){result();logo();sync();oauth();lang();settings();strip();loadFeatured();loadInternalI18n()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();})();
