(function(){'use strict';
var API=(window.SAKAN_API_BASE||localStorage.getItem('sakanApiBase')||'/api').replace(/\/$/,'');
var LANGS=[['ar','العربية'],['de','Deutsch'],['en','English'],['fr','Français'],['es','Español'],['it','Italiano'],['nl','Nederlands'],['pt','Português'],['tr','Türkçe'],['ru','Русский'],['uk','Українська'],['pl','Polski'],['sv','Svenska'],['da','Dansk'],['no','Norsk'],['fi','Suomi'],['el','Ελληνικά'],['ro','Română'],['cs','Čeština'],['hu','Magyar']];
function loadFeatured(){if(!/\/home\.html$/.test(location.pathname)||document.getElementById('sakanFeaturedScript'))return;var s=document.createElement('script');s.id='sakanFeaturedScript';s.src='../js/featured-ads.js';s.defer=true;document.body.appendChild(s)}
function loadInternalI18n(){if(document.getElementById('sakanInternalI18n'))return;var s=document.createElement('script');s.id='sakanInternalI18n';s.src='../js/internal-i18n.js';s.defer=true;document.body.appendChild(s)}
function saveUser(u){if(!u)return;localStorage.setItem('sakanCurrentUser',JSON.stringify(u));localStorage.setItem('sakanProfileData',JSON.stringify({realName:u.realName||'',displayName:u.displayName||'',gender:u.gender||'',birthDate:u.birthDate||'',age:u.age||'',country:u.country||'',city:u.city||'',maritalStatus:u.maritalStatus||'',language:u.language||u.preferredLanguage||'ar',education:u.education||'',profession:u.profession||'',aboutMe:u.aboutMe||'',lookingFor:u.lookingFor||'',showRealName:!!u.showRealName,preferredLanguage:u.preferredLanguage||u.language||'ar'}))}
function logo(){document.querySelectorAll('img[alt*="شعار منصة سكن"],.logo-mark img,.brand-icon img,.logo-circle img').forEach(function(i){if(i.dataset.fix)return;i.dataset.fix=1;var a=['../assets/sakan-logo.png','/frontend/assets/sakan-logo.png','/assets/sakan-logo.png'];i.addEventListener('error',function(){var n=Number(i.dataset.n||0);if(n<3){i.src=a[n];i.dataset.n=n+1}});if(!i.complete||!i.naturalWidth)i.src=a[0]})}
function sync(){var t=localStorage.getItem('sakanAuthToken'),raw=localStorage.getItem('sakanCurrentUser');if(raw){try{saveUser(JSON.parse(raw))}catch(e){}}if(!t||sessionStorage.getItem('sakanSync'))return;sessionStorage.setItem('sakanSync','1');fetch(API+'/me',{headers:{Authorization:'Bearer '+t}}).then(function(r){return r.ok?r.json():null}).then(function(d){if(d&&d.user)saveUser(d.user)}).catch(function(){})}
function oauth(){document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('#googleBtn,#facebookBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();location.assign(API+'/auth/oauth/'+(b.id==='googleBtn'?'google':'facebook')+'/start')},true)}
function lang(){return;}
function settings(){document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('.tool-card[data-tool="settings"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();location.href='settings.html'},true)}
function strip(){var t=document.getElementById('stripTrack');if(!t)return;function clean(){Array.from(t.querySelectorAll('img')).forEach(function(i){var s=((i.getAttribute('src')||'')+' '+(i.getAttribute('alt')||'')).toLowerCase();if(/sakan-logo|logo|شعار|sakan.*brand|brand.*sakan/.test(s))i.closest('.mini-member')?.remove()});t.style.animationDuration='600s';t.style.animationTimingFunction='linear';t.style.animationIterationCount='infinite'}clean();var observer=new MutationObserver(clean);observer.observe(t,{childList:true,subtree:true})}
function result(){var p=new URLSearchParams(location.search),t=p.get('oauth_token');if(t){localStorage.setItem('sakanAuthToken',t);localStorage.setItem('sakanLoggedIn','true');p.delete('oauth_token');history.replaceState({},document.title,location.pathname+(p.toString()?'?'+p.toString():''));location.href='/frontend/pages/home.html'}}
function start(){result();logo();sync();oauth();lang();settings();strip();loadFeatured();loadInternalI18n()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();})();
