"""auto update

Revision ID: f517ebecab7c
Revises: 7f92d43577bb
Create Date: 2026-09-21 01:25:00.007528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f517ebecab7c'
down_revision: Union[str, Sequence[str], None] = '7f92d43577bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presences', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_presences_user_id'), 'presences', ['user_id'], unique=False)
    op.add_column('promotions', sa.Column('user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_promotions_user_id'), 'promotions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotions_user_id'), table_name='promotions')
    op.drop_column('promotions', 'user_id')
    op.drop_index(op.f('ix_presences_user_id'), table_name='presences')
    op.drop_column('presences', 'user_id')
    # ### end Alembic commands ###